trigger: none

resources:
  repositories:
    - repository: PipelineScripts
      type: git
      name: Platform/PipelineScripts
      ref: refs/heads/PLT-14216_coturn_secret_configure

pool:
  vmImage: ubuntu-latest

variables:
- name: imageName
  value: livekit-signal-proxy
- name: containerRegistry
  value: 'ACR_RW1APPCONTAINERS'

stages:
  - stage: Build_base
    displayName: Build base Image
    jobs:
    - template: templates/jobs/build_base-docker-image.yml@PipelineScripts
      parameters:
        acr_connection_name: '$(containerRegistry)'
        trivy_acr_connection_name: '$(containerRegistry)'
        image_name: '$(imageName)'
        dockerfile: 'Dockerfile'
        skipSonarScan: true
        skipDepTrackScan: true
        multistageBuilds: false

  - template: pipelines/livekit-signal-proxy-cd.yml@PipelineScripts