# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  repositories:
    - repository: PipelineScripts
      type: git
      name: Platform/PipelineScripts
      ref: refs/heads/develop

pool:
  vmImage: ubuntu-latest

variables:
- name: imageName
  value: livekit-signal-proxy
- name: containerRegistry
  value: 'ACR_RW1APPCONTAINERS'

steps:
- task: Docker@2
  displayName: 'Build docker image'
  retryCountOnTaskFailure: 3
  inputs:
    containerRegistry: '$(containerRegistry)'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: '$(Build.BuildId)'
    addBaseImageData: false

- template: templates/steps/trivy_scan.yml@PipelineScripts
  parameters:
    image_name: '$(imageName)'
    docker_registry_name: rw1appcontainers.azurecr.io

- task: Docker@2
  displayName: 'Push docker image'
  inputs:
    containerRegistry: '$(containerRegistry)'
    repository: '$(imageName)'
    command: 'push'
    tags: '$(Build.BuildId)'